import type { FilterItem, VechicleInfo, VechicleList } from "./lib/types";

export const vechicleList: VechicleList = [
  { id: 1, regNr: "ABC-123", code: "CAR" },
  { id: 2, regNr: "BXY-987", code: "TRUCK" },
  { id: 3, regNr: "MOTO-45", code: "MOTORCYCLE" },
  { id: 4, regNr: "VAN-202", code: "VAN" },
  { id: 5, regNr: "BUS-12", code: "BUS" },
  { id: 6, regNr: "EV-001", code: "CAR" },
  { id: 7, regNr: "LT-777", code: "CAR" },
  { id: 8, regNr: "TRK-314", code: "TRUCK" },
  { id: 9, regNr: "MC-900", code: "MOTORCYCLE" },
  { id: 10, regNr: "CARGO-5", code: "VAN" },
  { id: 11, regNr: "DLX-112", code: "CAR" },
  { id: 12, regNr: "HTR-221", code: "TRUCK" },
  { id: 13, regNr: "SMB-333", code: "BUS" },
  { id: 14, regNr: "MOTO-777", code: "MOTORCYCLE" },
  { id: 15, regNr: "VNX-888", code: "VAN" },
  { id: 16, regNr: "ECO-101", code: "CAR" },
  { id: 17, regNr: "HVY-909", code: "TRUCK" },
  { id: 18, regNr: "SHU-055", code: "BUS" },
  { id: 19, regNr: "SC-002", code: "MOTORCYCLE" },
  { id: 20, regNr: "PSG-404", code: "VAN" },
];

export const vechicleInfo: VechicleInfo[] = [
  {
    id: 1,
    make: "Toyota",
    model: "Corolla",
    year: 2020,
    regNr: "ABC-123",
    code: "CAR",
  },
  {
    id: 2,
    make: "Ford",
    model: "F-150",
    year: 2021,
    regNr: "BXY-987",
    code: "TRUCK",
  },
  {
    id: 3,
    make: "Honda",
    model: "CBR600RR",
    year: 2019,
    regNr: "MOTO-45",
    code: "MOTORCYCLE",
  },
  {
    id: 4,
    make: "Mercedes-Benz",
    model: "Sprinter",
    year: 2022,
    regNr: "VAN-202",
    code: "VAN",
  },
  {
    id: 5,
    make: "Volvo",
    model: "7900 Electric",
    year: 2020,
    regNr: "BUS-12",
    code: "BUS",
  },
  {
    id: 6,
    make: "Tesla",
    model: "Model 3",
    year: 2021,
    regNr: "EV-001",
    code: "CAR",
  },
  {
    id: 7,
    make: "Volkswagen",
    model: "Golf",
    year: 2018,
    regNr: "LT-777",
    code: "CAR",
  },
  {
    id: 8,
    make: "Volvo",
    model: "FH16",
    year: 2020,
    regNr: "TRK-314",
    code: "TRUCK",
  },
  {
    id: 9,
    make: "Honda",
    model: "CBR600RR",
    year: 2019,
    regNr: "MC-900",
    code: "MOTORCYCLE",
  },
  {
    id: 10,
    make: "Volkswagen",
    model: "Transporter",
    year: 2021,
    regNr: "CARGO-5",
    code: "VAN",
  },
  {
    id: 11,
    make: "BMW",
    model: "3 Series",
    year: 2022,
    regNr: "DLX-112",
    code: "CAR",
  },
  {
    id: 12,
    make: "Scania",
    model: "R450",
    year: 2021,
    regNr: "HTR-221",
    code: "TRUCK",
  },
  {
    id: 13,
    make: "MAN",
    model: "A95",
    year: 2020,
    regNr: "SMB-333",
    code: "BUS",
  },
  {
    id: 14,
    make: "Yamaha",
    model: "YZF-R7",
    year: 2022,
    regNr: "MOTO-777",
    code: "MOTORCYCLE",
  },
  {
    id: 15,
    make: "Renault",
    model: "Master",
    year: 2019,
    regNr: "VNX-888",
    code: "VAN",
  },
  {
    id: 16,
    make: "Hyundai",
    model: "Elantra",
    year: 2021,
    regNr: "ECO-101",
    code: "CAR",
  },
  {
    id: 17,
    make: "DAF",
    model: "XF",
    year: 2022,
    regNr: "HVY-909",
    code: "TRUCK",
  },
  {
    id: 18,
    make: "Isuzu",
    model: "Citibus",
    year: 2020,
    regNr: "SHU-055",
    code: "BUS",
  },
  {
    id: 19,
    make: "Suzuki",
    model: "GSX-S1000",
    year: 2021,
    regNr: "SC-002",
    code: "MOTORCYCLE",
  },
  {
    id: 20,
    make: "Fiat",
    model: "Ducato",
    year: 2020,
    regNr: "PSG-404",
    code: "VAN",
  },
];

export const classificators: FilterItem[] = [
  {
    code: "CAR",
    name: "Lengvasis automobilis",
  },
  {
    code: "BUS",
    name: "Autobusas",
  },
  {
    code: "TRUCK",
    name: "Sunkvežimis",
  },
  {
    code: "MOTORCYCLE",
    name: "Motoroleris",
  },
  {
    code: "VAN",
    name: "Keleivinis mikroautobusas",
  },
];
